AWSTemplateFormatVersion: '2010-09-09'
Description: A-New-Startup EKS - CodeCommit repos, ECR Repos, and S3 bucket used by the CI/CD Pipeline

Parameters:
  Prefix:
    Type: String
    Default: a-new-startup-eks
    Description: "A Prefix to use on the resource names."
  
  Bucket:
    Type: String
    Description: "A private S3 bucket where we can temporarily house a zip of source code."
    
Resources:
  
  # The A-New-Startup application code will be stored here.  
  AppSourceRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: "The A-New-Startup application code (for EKS) - used in a CI/CD pipeline"
      # For CodeCommit, we must generate a unique name.  CloudFormation will not do it for us!
      # This is incorporating part of the StackId - which will be unique (often enough)
      RepositoryName: !Join ['-', [!Ref Prefix, 'AppSourceRepo', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      Code:
        BranchName: main
        S3:
          Bucket: !Ref Bucket
          Key: a-new-startup.zip
  
  # Source code for the Helm chart will go here.        
  ChartSourceRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: "The A-New-Startup Helm Chart code - used in a CI/CD pipeline"
      # For CodeCommit, we must generate a unique name.  CloudFormation will not do it for us!
      # This is incorporating part of the StackId - which will be unique (often enough)
      RepositoryName: !Join ['-', [!Ref Prefix, 'ChartSourceRepo', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      Code:
        BranchName: main
        S3:
          Bucket: !Ref Bucket
          Key: a-new-startup-helm.zip

  # ECR Repo for the Container Image we'll be creating.
  AppImage:
    Type: AWS::ECR::Repository
    # CloudFormation will generate a dynamic name for us!       
    
  # Helm charts will be stored in this s3 bucket.  
  HelmChartRepo:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

Outputs:

  AppSourceRepo:
    Value: !GetAtt AppSourceRepo.Name
    Export:
      Name: !Join ['-', [!Ref Prefix, 'AppSourceRepo']]
      
  ChartSourceRepo:
    Value: !GetAtt ChartSourceRepo.Name
    Export:
      Name: !Join ['-', [!Ref Prefix, 'ChartSourceRepo']]

  HelmChartRepo:
    Value: !Ref HelmChartRepo
    Export:
      Name: !Join ['-', [!Ref Prefix, 'HelmChartRepo']]

  AppImage:
    Value: !Ref AppImage
    Export:
      Name: !Join ['-', [!Ref Prefix, 'AppImage']]